from . import appointment_device_line
from . import appointment
from . import appointment_complete_wizard
from . import account_move
from . import account_move_line
from . import account_payment
from . import account_payment_register
from . import product_template
from . import ear_mould_form
from . import audiometry_result
from . import audiometry_result_mark