{
    "name": "Resonnocare Front Desk",
    "version": "18.0.1.0.0",
    "category": "Resonnocare",
    "summary": "Front Desk operations for Resonnocare clinics",
    "description": """
    Front Desk interface for Resonnocare ERP.
    Provides patient registration, appointment handling, and check-in workflows.
    """,
    "depends": [
        "base",
        "resonnocare_base",
        "resonnocare_clinic",
        "resonnocare_hr",
        "resonnocare_master",
        "resonnocare_inventory",
        "sale",
        "crm",
    ],
    "data": [
        "data/patient_sequence.xml",
        "data/discount_approval_request_sequence.xml",
        "data/advance_approval_request_sequence.xml",
        "data/final_invoice_sequence.xml",
        "data/sale_return_request_sequence.xml",
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/res_partner_patient_form.xml",
        "views/patient_search_view.xml",
        "views/patient_registration_wizard.xml",
        "wizard/patient_search_wizard.xml",
        "views/dashboard_view.xml",
        "views/clinic_ops_views.xml",
        "views/server_actions.xml",
        "views/sale_order_view.xml",
        "views/sale_advance_payment_inv_views.xml",
        "views/discount_approval_request_views.xml",
        "views/advance_approval_request_views.xml",
        "views/report_final_invoice.xml",
        "views/sale_return_request_views.xml",
        "views/sale_order_return_views.xml",
        "wizard/sale_return_wizard.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
    "license": "LGPL-3",
}
