{
    "name": "Resonnocare HR",
    "version": "18.0.1.0.0",
    "category": "Resonnocare",
    "summary": "HR & Employee management for Resonnocare",
    "depends": [
        "hr",
        "hr_attendance",
        "hr_holidays",
        "payroll",
        "mail",
        "resonnocare_base",
        "resonnocare_admin",
        "resonnocare_clinic",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/employee_sequence.xml",
        "data/attendance_cron.xml",
        "data/attendance_cycle_cron.xml",
        "data/attendance_regularization_cron.xml",
        "data/leave_workflow_cron.xml",
        "data/joining_stage_sla_cron.xml",
        "data/payroll_claim_sequence.xml",
        "data/payroll_disbursement_sequence.xml",
        "data/payroll_process_cron.xml",
        "views/hr_employee_views.xml",
        "views/hr_leave_views.xml",
        "views/hr_handbook_views.xml",
        "views/hr_handbook_wizard_views.xml",
        "views/res_users_profile_views.xml",
        "views/hr_self_service_views.xml",
        "views/hr_attendance_views.xml",
        "views/attendance_summary_views.xml",
        "views/attendance_policy_views.xml",
        "views/holiday_calendar_views.xml",
        "views/attendance_regularization_views.xml",
        "views/payroll_claim_views.xml",
        "views/payroll_process_views.xml",
        "views/payroll_reports.xml",
        "views/uat_checklist_views.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
    'license': 'LGPL-3',
}
