{
    "name": "Resonnocare Clinic",
    "version": "18.0.1.0.0",
    "category": "Resonnocare",
    "summary": "Clinic (RC / Store) management for Resonnocare",
    "depends": [
        "base",
        "hr",
        "stock",
        "product_expiry",
        "resonnocare_base",
        "resonnocare_admin",
        "resonnocare_master",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/clinic_sequence.xml",
        "data/clinic_cron.xml",
        "views/clinic_create_wizard_view.xml",
        "views/clinic_views.xml",
        "views/res_users_views.xml",
        "views/res_company_views.xml",
        "views/hr_department_views.xml",
        "views/menu.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
    "auto_install": False,
    "license": "LGPL-3",
}
