from odoo import api, fields, models
from odoo.exceptions import ValidationError
from odoo.tools import float_is_zero
from odoo.fields import Command


class ResonnocareFinalInvoice(models.Model):
    _name = "resonnocare.final.invoice"
    _description = "Resonnocare Final Invoice Document"
    _order = "id desc"

    name = fields.Char(
        string="Final Invoice No.",
        required=True,
        copy=False,
        readonly=True,
        default="/",
    )
    sale_order_id = fields.Many2one("sale.order", string="Sale Order", required=True, ondelete="cascade")
    partner_id = fields.Many2one(related="sale_order_id.partner_id", store=True, readonly=True)
    company_id = fields.Many2one(related="sale_order_id.company_id", store=True, readonly=True)
    clinic_id = fields.Many2one(related="sale_order_id.clinic_id", store=True, readonly=True)
    invoice_origin = fields.Char(related="sale_order_id.name", store=True, readonly=True)
    invoice_date = fields.Date(string="Invoice Date", required=True, default=fields.Date.today)
    customer_name = fields.Char(string="Customer", readonly=True)
    customer_phone = fields.Char(string="Customer Contact", readonly=True)
    customer_address = fields.Char(string="Customer Address", readonly=True)
    patient_name = fields.Char(string="Patient", readonly=True)
    clinic_name = fields.Char(string="Clinic", readonly=True)
    gst_treatment = fields.Char(string="GST Treatment", readonly=True)
    currency_id = fields.Many2one("res.currency", string="Currency", required=True, readonly=True)
    total_payable = fields.Monetary(string="Total Payable", currency_field="currency_id", readonly=True)
    amount_untaxed = fields.Monetary(string="Untaxed Amount", currency_field="currency_id", readonly=True)
    amount_total = fields.Monetary(string="Amount Total", currency_field="currency_id", readonly=True)
    total_paid = fields.Monetary(string="Total Paid", currency_field="currency_id", readonly=True)
    balance_due = fields.Monetary(string="Balance Due", currency_field="currency_id", readonly=True)
    amount_total_words = fields.Char(string="Amount Total (Words)", compute="_compute_amount_total_words")
    generated_by_id = fields.Many2one("res.users", string="Generated By", readonly=True)
    line_ids = fields.One2many(
        "resonnocare.final.invoice.line",
        "final_invoice_id",
        string="Invoice Lines",
        copy=False,
    )

    @api.model_create_multi
    def create(self, vals_list):
        seq = self.env["ir.sequence"]
        for vals in vals_list:
            if not vals.get("name") or vals["name"] == "/":
                vals["name"] = seq.next_by_code("resonnocare.final.invoice") or "/"
        return super().create(vals_list)

    def action_print_document(self):
        self.ensure_one()
        return self.env.ref("resonnocare_frontdesk.action_report_final_invoice_document").report_action(self)

    @api.depends("amount_total", "currency_id")
    def _compute_amount_total_words(self):
        for rec in self:
            if rec.currency_id:
                rec.amount_total_words = rec.currency_id.amount_to_text(rec.amount_total or 0.0)
            else:
                rec.amount_total_words = ""

    def _is_taxable_move(self):
        self.ensure_one()
        return any((l.cgst_amount or l.sgst_amount or l.igst_amount) > 0 for l in self.line_ids)

    def _format_amount_compact(self, amount):
        self.ensure_one()
        value = amount or 0.0
        text = f"{value:,.2f}"
        if "." in text:
            text = text.rstrip("0").rstrip(".")
        return text

    def _next_custom_final_invoice_name(self, reference_invoice, is_taxable=True):
        doc_code = "TI" if is_taxable else "BS"
        if reference_invoice and hasattr(reference_invoice, "_get_custom_billing_code"):
            billing_code = reference_invoice._get_custom_billing_code()
        else:
            billing_code = "C"
        if reference_invoice and hasattr(reference_invoice, "_get_custom_state_code"):
            state_code = reference_invoice._get_custom_state_code()
        else:
            state_code = "NA"
        if reference_invoice and hasattr(reference_invoice, "_get_invoice_fy_suffix"):
            fy_suffix = reference_invoice._get_invoice_fy_suffix()
        else:
            today = fields.Date.today()
            fy_end_year = today.year + 1 if today.month >= 4 else today.year
            fy_suffix = str(fy_end_year)[-2:]

        seq_code = f"resonnocare.final.inv.{doc_code}.{billing_code}.{state_code}.{fy_suffix}"
        seq_prefix = f"{doc_code}/{billing_code}/{state_code}/{fy_suffix}/"
        sequence = self.env["ir.sequence"].sudo().search([("code", "=", seq_code)], limit=1)
        if not sequence:
            sequence = self.env["ir.sequence"].sudo().create(
                {
                    "name": f"Resonnocare Final {seq_prefix}",
                    "code": seq_code,
                    "prefix": seq_prefix,
                    "padding": 5,
                    "implementation": "no_gap",
                    "company_id": False,
                }
            )
        return sequence.next_by_id()

    def _get_b2c_report_lines(self):
        self.ensure_one()
        rows = []
        for idx, line in enumerate(self.line_ids, start=1):
            rows.append(
                {
                    "sl_no": idx,
                    "description": line.description or "",
                    "serial_numbers": line.serial_numbers or "",
                    "hsn": line.hsn_code or "",
                    "item_code": line.item_code or "",
                    "brand": line.brand_name or "",
                    "qty": line.quantity or 0.0,
                    "mrp": line.mrp or 0.0,
                    "total": line.line_total or 0.0,
                    "discount": line.discount_amount or 0.0,
                    "taxable_value": line.taxable_value or 0.0,
                    "cgst_rate": line.cgst_rate or 0.0,
                    "cgst_amount": line.cgst_amount or 0.0,
                    "sgst_rate": line.sgst_rate or 0.0,
                    "sgst_amount": line.sgst_amount or 0.0,
                    "igst_rate": line.igst_rate or 0.0,
                    "igst_amount": line.igst_amount or 0.0,
                    "gst_rate_total": (line.cgst_rate or 0.0) + (line.sgst_rate or 0.0) + (line.igst_rate or 0.0),
                }
            )
        return rows

    def _get_b2b_report_lines(self):
        self.ensure_one()
        rows = []
        for idx, line in enumerate(self.line_ids, start=1):
            rows.append(
                {
                    "sl_no": idx,
                    "description": line.description or "",
                    "serial_numbers": line.serial_numbers or "",
                    "hsn": line.hsn_code or "",
                    "item_code": line.item_code or "",
                    "brand": line.brand_name or "",
                    "qty": line.quantity or 0.0,
                    "patient_selling_price": line.mrp or 0.0,
                    "hospital_sharing_pct": line.hospital_sharing_pct or 0.0,
                    "hospital_sharing_amount": line.hospital_sharing_amount or 0.0,
                    "invoice_value": line.taxable_value or 0.0,
                    "cgst_rate": line.cgst_rate or 0.0,
                    "cgst_amount": line.cgst_amount or 0.0,
                    "sgst_rate": line.sgst_rate or 0.0,
                    "sgst_amount": line.sgst_amount or 0.0,
                    "igst_rate": line.igst_rate or 0.0,
                    "igst_amount": line.igst_amount or 0.0,
                    "gst_rate_total": (line.cgst_rate or 0.0) + (line.sgst_rate or 0.0) + (line.igst_rate or 0.0),
                    "gross": line.line_total or 0.0,
                    "taxable_value": line.taxable_value or 0.0,
                }
            )
        return rows

    def _get_b2c_hsn_summary(self):
        self.ensure_one()
        summary = {}
        for row in self._get_b2c_report_lines():
            key = (row["hsn"] or "", row["gst_rate_total"] or 0.0)
            if key not in summary:
                summary[key] = {"hsn": key[0], "qty": 0.0, "rate": key[1], "taxable_value": 0.0}
            summary[key]["qty"] += row["qty"]
            summary[key]["taxable_value"] += row["taxable_value"]
        return list(summary.values())

    def _get_b2b_hsn_summary(self):
        self.ensure_one()
        summary = {}
        for row in self._get_b2b_report_lines():
            key = (row["hsn"] or "", row["gst_rate_total"] or 0.0)
            if key not in summary:
                summary[key] = {"hsn": key[0], "qty": 0.0, "rate": key[1], "taxable_value": 0.0}
            summary[key]["qty"] += row["qty"]
            summary[key]["taxable_value"] += row["taxable_value"]
        return list(summary.values())

    def _get_b2c_payment_lines(self):
        self.ensure_one()
        result = []
        invoices = self.sale_order_id.invoice_ids.filtered(
            lambda inv: inv.move_type == "out_invoice" and inv.state == "posted"
        )
        payments = (invoices.mapped("reconciled_payment_ids") | invoices.mapped("matched_payment_ids")).sorted(
            lambda p: (p.date or fields.Date.context_today(self), p.id)
        )
        for idx, payment in enumerate(payments, start=1):
            pay_amt = payment.amount or 0.0
            if payment.currency_id and payment.currency_id != self.currency_id:
                pay_amt = payment.currency_id._convert(
                    payment.amount or 0.0,
                    self.currency_id,
                    self.company_id,
                    payment.date or self.invoice_date or fields.Date.context_today(self),
                )
            result.append(
                {
                    "sl_no": idx,
                    "receipt_no": payment.name or "",
                    "paid_on": payment.date,
                    "payment_mode": payment.journal_id.name or "",
                    "reference": getattr(payment, "payment_ref", False) or getattr(payment, "ref", False) or "",
                    "cheque_date": (payment.cheque_date if hasattr(payment, "cheque_date") else False),
                    "amount": pay_amt,
                }
            )
        return result

    @api.model
    def create_or_refresh_from_sale_order(self, sale):
        sale = sale.sudo()
        FinalInvoice = self.sudo()
        if sale.state not in ("sale", "done"):
            raise ValidationError("Final invoice is allowed only for confirmed sales.")

        invoices = sale.invoice_ids.filtered(
            lambda inv: inv.move_type == "out_invoice" and inv.state == "posted"
        )
        total_paid = 0.0
        for inv in invoices:
            if hasattr(inv, "_get_contract_advance_paid"):
                total_paid += inv._get_contract_advance_paid()
            else:
                total_paid += (inv.amount_total or 0.0) - (inv.amount_residual or 0.0)

        # For final invoice, always generate the custom TI/BS style number.
        # Device normal invoices may use Odoo default numbering; final document carries custom number.
        reference_invoice = False
        non_downpayment_invoices = invoices.filtered(
            lambda inv: bool(
                inv.invoice_line_ids.filtered(
                    lambda l: not l.display_type and not getattr(l, "is_downpayment", False)
                )
            )
        )
        if non_downpayment_invoices:
            reference_invoice = non_downpayment_invoices.sorted(
                lambda inv: (inv.invoice_date or fields.Date.today(), inv.id)
            )[-1]
        elif invoices:
            reference_invoice = invoices.sorted(lambda inv: (inv.invoice_date or fields.Date.today(), inv.id))[-1]

        currency = sale.currency_id or sale.company_id.currency_id
        total_payable = sale.amount_total or 0.0
        balance_due = total_payable - total_paid
        if balance_due < 0:
            balance_due = 0.0
        if not float_is_zero(balance_due, precision_rounding=(currency.rounding or 0.01)):
            raise ValidationError("Final invoice can be printed only after full payment is completed.")

        product_lines = sale.order_line.filtered(
            lambda l: not l.display_type
            and l.product_id
            and (getattr(l.product_id, "type", "") in ("product", "consu"))
        )
        product_lines = product_lines.filtered(lambda l: not getattr(l, "is_downpayment", False))
        if not product_lines:
            raise ValidationError(
                "No goods/device lines found to generate final invoice. "
                "Final invoice is only for device/goods sale (not service/contract lines)."
            )

        is_taxable = bool(any((line.tax_id.filtered(lambda t: (t.amount or 0.0) > 0)) for line in product_lines))

        existing_doc = FinalInvoice.search([("sale_order_id", "=", sale.id)], order="id desc", limit=1)
        if existing_doc and existing_doc.name and existing_doc.name != "/":
            final_doc_name = existing_doc.name
        else:
            final_doc_name = FinalInvoice._next_custom_final_invoice_name(reference_invoice, is_taxable=is_taxable)

        vals = {
            "sale_order_id": sale.id,
            "name": final_doc_name or "/",
            "invoice_date": fields.Date.today(),
            "customer_name": sale.partner_id.display_name or "",
            "customer_phone": sale.partner_id.mobile or sale.partner_id.phone or "",
            "customer_address": sale.partner_id.contact_address or "",
            "patient_name": sale.patient_id.display_name or "",
            "clinic_name": (sale.clinic_id.display_name if sale.clinic_id else ""),
            "gst_treatment": (
                sale.partner_id._fields.get("l10n_in_gst_treatment")
                and dict(sale.partner_id._fields["l10n_in_gst_treatment"].selection).get(
                    sale.partner_id.l10n_in_gst_treatment
                )
            )
            or "Consumer",
            "currency_id": currency.id,
            "total_payable": total_payable,
            "amount_untaxed": sum(product_lines.mapped("price_subtotal")),
            "amount_total": total_payable,
            "total_paid": total_paid,
            "balance_due": balance_due,
            "generated_by_id": self.env.user.id,
            "line_ids": [Command.clear()],
        }
        for line in product_lines:
            tax_rate = sum(line.tax_id.mapped("amount")) if line.tax_id else 0.0
            taxable_value = line.price_subtotal or 0.0
            tax_amount = (line.price_total or 0.0) - taxable_value
            same_state = (
                sale.company_id.state_id
                and sale.partner_id.state_id
                and sale.company_id.state_id.id == sale.partner_id.state_id.id
            )
            cgst_rate = (tax_rate / 2.0) if same_state else 0.0
            sgst_rate = (tax_rate / 2.0) if same_state else 0.0
            igst_rate = tax_rate if not same_state else 0.0
            cgst_amount = (tax_amount / 2.0) if same_state else 0.0
            sgst_amount = (tax_amount / 2.0) if same_state else 0.0
            igst_amount = tax_amount if not same_state else 0.0
            
            # Only extract serial numbers for HA (Hearing Aid) and Charger (Equipment) products
            serial_numbers = ""
            if line.product_id.item_type in ('ha', 'equipment'):
                serial_names = []
                for move in line.move_ids.filtered(lambda m: m.state == "done"):
                    serial_names.extend(move.move_line_ids.mapped("lot_id.name"))
                serial_numbers = ", ".join(dict.fromkeys([s for s in serial_names if s]))
                if not serial_numbers:
                   raise ValidationError(
                        "Serial Number is mandatory for Final Invoice. "
                        "Please complete delivery with serial for product '%s'." % (line.product_id.display_name,)
                    )

            # serial_names = []
            # for move in line.move_ids.filtered(lambda m: m.state == "done"):
            #     serial_names.extend(move.move_line_ids.mapped("lot_id.name"))
            # serial_numbers = ", ".join(dict.fromkeys([s for s in serial_names if s]))
            # if not serial_numbers:
                # raise ValidationError(
                #     "Serial Number is mandatory for Final Invoice. "
                #     "Please complete delivery with serial for product '%s'." % (line.product_id.display_name,)
                # )
            
            vals["line_ids"].append(
                Command.create(
                    {
                        "product_id": line.product_id.id,
                        "description": line.name or line.product_id.display_name,
                        "serial_numbers": serial_numbers,
                        "hsn_code": (line.product_id.l10n_in_hsn_code or ""),
                        "item_code": (line.product_id.default_code or ""),
                        "brand_name": (line.product_id.product_brand_id.name if "product_brand_id" in line.product_id._fields and line.product_id.product_brand_id else ""),
                        "quantity": line.product_uom_qty or 0.0,
                        "mrp": line.price_unit or 0.0,
                        "line_total": (line.product_uom_qty or 0.0) * (line.price_unit or 0.0),
                        "unit_price": line.price_unit or 0.0,
                        "discount_pct": line.discount or 0.0,
                        "discount_amount": ((line.product_uom_qty or 0.0) * (line.price_unit or 0.0)) - taxable_value,
                        "taxable_value": taxable_value,
                        "cgst_rate": cgst_rate,
                        "cgst_amount": cgst_amount,
                        "sgst_rate": sgst_rate,
                        "sgst_amount": sgst_amount,
                        "igst_rate": igst_rate,
                        "igst_amount": igst_amount,
                        "subtotal": line.price_total or 0.0,
                        "hospital_sharing_pct": (
                            line.clinic_sharing_pct
                            if "clinic_sharing_pct" in line._fields
                            else 0.0
                        )
                        or 0.0,
                        "hospital_sharing_amount": (
                            line.clinic_sharing_amount
                            if "clinic_sharing_amount" in line._fields
                            else 0.0
                        )
                        or 0.0,
                    }
                )
            )

        if existing_doc:
            existing_doc.sudo().write(vals)
            doc = existing_doc
        else:
            doc = FinalInvoice.create(vals)
        return self.browse(doc.id)


class ResonnocareFinalInvoiceLine(models.Model):
    _name = "resonnocare.final.invoice.line"
    _description = "Resonnocare Final Invoice Line"
    _order = "id"

    final_invoice_id = fields.Many2one(
        "resonnocare.final.invoice",
        string="Final Invoice",
        required=True,
        ondelete="cascade",
    )
    product_id = fields.Many2one("product.product", string="Product", readonly=True)
    description = fields.Char(string="Description", readonly=True)
    serial_numbers = fields.Char(string="Serial Numbers", readonly=True)
    hsn_code = fields.Char(string="HSN/SAC", readonly=True)
    item_code = fields.Char(string="Item", readonly=True)
    brand_name = fields.Char(string="Brand", readonly=True)
    quantity = fields.Float(string="Qty", readonly=True)
    mrp = fields.Float(string="MRP", readonly=True)
    line_total = fields.Float(string="Total", readonly=True)
    unit_price = fields.Float(string="Unit Price", readonly=True)
    discount_pct = fields.Float(string="Discount %", readonly=True)
    discount_amount = fields.Float(string="Discount Amount", readonly=True)
    taxable_value = fields.Float(string="Taxable Value", readonly=True)
    cgst_rate = fields.Float(string="CGST %", readonly=True)
    cgst_amount = fields.Float(string="CGST Amount", readonly=True)
    sgst_rate = fields.Float(string="SGST %", readonly=True)
    sgst_amount = fields.Float(string="SGST Amount", readonly=True)
    igst_rate = fields.Float(string="IGST %", readonly=True)
    igst_amount = fields.Float(string="IGST Amount", readonly=True)
    subtotal = fields.Float(string="Subtotal", readonly=True)
    hospital_sharing_pct = fields.Float(string="Hospital Sharing %", readonly=True)
    hospital_sharing_amount = fields.Float(
        string="Hospital Sharing Amount", readonly=True
    )
